spring:
  profiles:
    active: dev
  datasource:
#    driver-class-name: com.alibaba.druid.proxy.DruidDriver
    type: com.alibaba.druid.pool.DruidDataSource
    #   数据源其他配置
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    #   配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    #    filters: stat,wall,log4j
    maxPoolPreparedStatementPerConnectionSize: 20
    useGlobalDataSourceStat: true
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
  thymeleaf:
    cache: false

mybatis:
  mapper-locations: classpath:mapper/*.xml

my:
  interceptor:
    flag: false

---
spring:
  profiles: prod
  datasource:
    username: root
    password: root
    url: jdbc:mysql://182.254.168.91:3306/blog?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.jdbc.Driver
my:
  interceptor:
    flag: true

---
spring:
  profiles: dev
  datasource:
    username: root
    password: root
    url: jdbc:mysql://127.0.0.1:3306/blog?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.jdbc.Driver
my:
  interceptor:
    flag: false